name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "hotnews"
database_id = "017b8f9e-742c-4d93-9ed1-529a69696dba"
